service: overRatesRevocationLoop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 512
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

functions:
  overRatesRevocationLoop:
    handler: index.handler
    reservedConcurrency: 1
    name: overRatesRevocationLoop
    description: ${env:VERSION_DESCRIPTION}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - OverRatesRevocationStartQueue
              - Arn
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: "overRatesRevocationLoop_${opt:stage, self:provider.stage}"

resources:
  Resources:
    OverRatesRevocationStartQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "over-rates-revocation-start.fifo"
        FifoQueue: true
        VisibilityTimeout: 1000
        ContentBasedDeduplication: true
    OverRatesRevocationTDHCalculatedSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):region}:987989283142:tdh-calculation-done.fifo
        Protocol: sqs
        Endpoint: !GetAtt
          - OverRatesRevocationStartQueue
          - Arn
        RawMessageDelivery: true
    OverRatesRevocationStartQueuePolicy:
      Type: "AWS::SQS::QueuePolicy"
      Properties:
        Queues:
          - Ref: "OverRatesRevocationStartQueue"
        PolicyDocument:
          Statement:
            - Effect: "Allow"
              Principal:
                Service: "sns.amazonaws.com"
              Action:
                - sqs:SendMessage
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueUrl
                - sqs:GetQueueAttributes
                - sqs:ListQueueTags
                - sqs:ChangeMessageVisibility
              Resource:
                - !GetAtt OverRatesRevocationStartQueue.Arn
    OverRatesRevocationLoopOOMFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: /aws/lambda/overRatesRevocationLoop
        FilterPattern: "Runtime.OutOfMemory"
        MetricTransformations:
          - MetricNamespace: "Lambda/OOM"
            MetricName: "overRatesRevocationLoop_OOMErrorCount"
            MetricValue: "1"
            DefaultValue: 0

    OverRatesRevocationLoopOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: OverRatesRevocationLoopOOMFilter
      Properties:
        AlarmName: !Sub "${AWS::StackName}-overRatesRevocationLoop-OOM"
        AlarmDescription: !Sub "Lambda overRatesRevocationLoop OutOfMemory in ${AWS::Region}"
        Namespace: "Lambda/OOM"
        MetricName: "overRatesRevocationLoop_OOMErrorCount"
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}