service: mintAnnouncementsLoop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 120
  architecture: arm64
  logRetentionInDays: 60

functions:
  mintAnnouncementsLoop:
    handler: index.handler
    name: mintAnnouncementsLoop
    description: ${env:VERSION_DESCRIPTION}
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    reservedConcurrency: 1
    events:
      - schedule: cron(40 17 ? * MON,WED,FRI *)
      - schedule: cron(30 18 ? * MON,WED,FRI *)
      - schedule: cron(0 19 ? * MON,WED,FRI *)
      - schedule: cron(20 19 ? * MON,WED,FRI *)
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: 'mintAnnouncementsLoop_${opt:stage, self:provider.stage}'

resources:
  Resources:
    MintAnnouncementsLoopLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/mintAnnouncementsLoop
        RetentionInDays: 60

    MintAnnouncementsLoopOOMFilter:
      Type: AWS::Logs::MetricFilter
      DependsOn: MintAnnouncementsLoopLogGroup
      Properties:
        LogGroupName: /aws/lambda/mintAnnouncementsLoop
        FilterPattern: "Runtime.OutOfMemory"
        MetricTransformations:
          - MetricNamespace: "Lambda/OOM"
            MetricName: "mintAnnouncementsLoop_OOMErrorCount"
            MetricValue: "1"
            DefaultValue: 0

    MintAnnouncementsLoopOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: MintAnnouncementsLoopOOMFilter
      Properties:
        AlarmName: !Sub "${AWS::StackName}-mintAnnouncementsLoop-OOM"
        AlarmDescription: !Sub "Lambda mintAnnouncementsLoop OutOfMemory in ${AWS::Region}"
        Namespace: "Lambda/OOM"
        MetricName: "mintAnnouncementsLoop_OOMErrorCount"
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
