service: xTdhStatsNormalisationLoop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

functions:
  xTdhStatsNormalisationLoop:
    handler: index.handler
    reservedConcurrency: 1
    name: xTdhStatsNormalisationLoop
    description: ${env:VERSION_DESCRIPTION}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - XTdhStatsNormalisationStartQueue
              - Arn
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: "xTdhStatsNormalisationLoop_${opt:stage, self:provider.stage}"

resources:
  Resources:
    XTdhStatsNormalisationLoopLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/xTdhStatsNormalisationLoop
        RetentionInDays: 60
    XTdhStatsNormalisationStartQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "xtdh-stats-normalisation-start.fifo"
        FifoQueue: true
        VisibilityTimeout: 1000
        ContentBasedDeduplication: true
    XTdhStatsNormalisationSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):region}:987989283142:tdh-calculation-done.fifo
        Protocol: sqs
        Endpoint: !GetAtt
          - XTdhStatsNormalisationStartQueue
          - Arn
        RawMessageDelivery: true
    XTdhStatsNormalisationStartQueuePolicy:
      Type: "AWS::SQS::QueuePolicy"
      Properties:
        Queues:
          - Ref: "XTdhStatsNormalisationStartQueue"
        PolicyDocument:
          Statement:
            - Effect: "Allow"
              Principal:
                Service: "sns.amazonaws.com"
              Action:
                - sqs:SendMessage
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueUrl
                - sqs:GetQueueAttributes
                - sqs:ListQueueTags
                - sqs:ChangeMessageVisibility
              Resource:
                - !GetAtt XTdhStatsNormalisationStartQueue.Arn
    XTdhStatsNormalisationLoopOOMFilter:
      Type: AWS::Logs::MetricFilter
      DependsOn:
        - XTdhStatsNormalisationLoopLogGroup
      Properties:
        LogGroupName:
          Ref: XTdhStatsNormalisationLoopLogGroup
        FilterPattern: "Runtime.OutOfMemory"
        MetricTransformations:
          - MetricNamespace: "Lambda/OOM"
            MetricName: "xTdhStatsNormalisationLoop_OOMErrorCount"
            MetricValue: "1"
            DefaultValue: 0

    XTdhStatsNormalisationLoopOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: XTdhStatsNormalisationLoopOOMFilter
      Properties:
        AlarmName: !Sub "${AWS::StackName}-xTdhStatsNormalisationLoop-OOM"
        AlarmDescription: !Sub "Lambda xTdhStatsNormalisationLoop OutOfMemory in ${AWS::Region}"
        Namespace: "Lambda/OOM"
        MetricName: "xTdhStatsNormalisationLoop_OOMErrorCount"
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}