service: nftHistoryLoop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 512
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

functions:
  nftHistoryLoop:
    handler: index.handler
    name: nftHistoryLoop
    description: ${env:VERSION_DESCRIPTION}
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    reservedConcurrency: 1
    events:
      - schedule: rate(30 minutes)
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: 'nftHistoryLoop_${opt:stage, self:provider.stage}'
      NFT_HISTORY_RESET: false

resources:
  Resources:
    NftHistoryLoopOOMFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: /aws/lambda/nftHistoryLoop
        FilterPattern: "Runtime.OutOfMemory"
        MetricTransformations:
          - MetricNamespace: "Lambda/OOM"
            MetricName: "nftHistoryLoop_OOMErrorCount"
            MetricValue: "1"
            DefaultValue: 0

    NftHistoryLoopOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: NftHistoryLoopOOMFilter
      Properties:
        AlarmName: !Sub "${AWS::StackName}-nftHistoryLoop-OOM"
        AlarmDescription: !Sub "Lambda nftHistoryLoop OutOfMemory in ${AWS::Region}"
        Namespace: "Lambda/OOM"
        MetricName: "nftHistoryLoop_OOMErrorCount"
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}