service: nftOwnersLoop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 2048
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

custom:
  chainIDs:
    staging: 1
    prod: 1

functions:
  nftOwnersLoop:
    handler: index.handler
    name: nftOwnersLoop
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: 'nftOwnersLoop_${opt:stage, self:provider.stage}'
      NEXTGEN_CHAIN_ID: ${self:custom.chainIDs.${opt:stage, self:provider.stage}, 1}
      NFT_OWNERS_RESET: false

resources:
  Resources:
    NftOwnersLoopLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/nftOwnersLoop
        RetentionInDays: 60
    NftOwnersLoopOOMFilter:
      Type: AWS::Logs::MetricFilter
      DependsOn:
        - NftOwnersLoopLogGroup
      Properties:
        LogGroupName:
          Ref: NftOwnersLoopLogGroup
        FilterPattern: 'Runtime.OutOfMemory'
        MetricTransformations:
          - MetricNamespace: 'Lambda/OOM'
            MetricName: 'nftOwnersLoop_OOMErrorCount'
            MetricValue: '1'
            DefaultValue: 0

    NftOwnersLoopOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: NftOwnersLoopOOMFilter
      Properties:
        AlarmName: !Sub '${AWS::StackName}-nftOwnersLoop-OOM'
        AlarmDescription: !Sub 'Lambda nftOwnersLoop OutOfMemory in ${AWS::Region}'
        Namespace: 'Lambda/OOM'
        MetricName: 'nftOwnersLoop_OOMErrorCount'
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
