service: refreshENS

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

functions:
  refreshENS:
    handler: index.handler
    name: refreshENS
    description: ${env:VERSION_DESCRIPTION}
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    reservedConcurrency: 1
    events:
      - schedule: rate(6 hours)
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: "refreshENS_${opt:stage, self:provider.stage}"
      
resources:
  Resources:
    RefreshENSOOMFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: /aws/lambda/refreshENS
        FilterPattern: "Runtime.OutOfMemory"
        MetricTransformations:
          - MetricNamespace: "Lambda/OOM"
            MetricName: "refreshENS_OOMErrorCount"
            MetricValue: "1"
            DefaultValue: 0

    RefreshENSOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: RefreshENSOOMFilter
      Properties:
        AlarmName: !Sub "${AWS::StackName}-refreshENS-OOM"
        AlarmDescription: !Sub "Lambda refreshENS OutOfMemory in ${AWS::Region}"
        Namespace: "Lambda/OOM"
        MetricName: "refreshENS_OOMErrorCount"
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}