service: dbMigrationsLoop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 512
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

functions:
  dbMigrationsLoop:
    handler: index.handler
    name: dbMigrationsLoop
    description: ${env:VERSION_DESCRIPTION}
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    reservedConcurrency: 1
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: "dbMigrationsLoop_{opt:stage, self:provider.stage}"
      
resources:
  Resources:
    DbMigrationsLoopOOMFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: /aws/lambda/dbMigrationsLoop
        FilterPattern: "Runtime.OutOfMemory"
        MetricTransformations:
          - MetricNamespace: "Lambda/OOM"
            MetricName: "dbMigrationsLoop_OOMErrorCount"
            MetricValue: "1"
            DefaultValue: 0

    DbMigrationsLoopOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: DbMigrationsLoopOOMFilter
      Properties:
        AlarmName: !Sub "${AWS::StackName}-dbMigrationsLoop-OOM"
        AlarmDescription: !Sub "Lambda dbMigrationsLoop OutOfMemory in ${AWS::Region}"
        Namespace: "Lambda/OOM"
        MetricName: "dbMigrationsLoop_OOMErrorCount"
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}