service: rateEventProcessingLoop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

functions:
  rateEventProcessingLoop:
    handler: index.handler
    name: rateEventProcessingLoop
    description: ${env:VERSION_DESCRIPTION}
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: "rateEventProcessingLoop_${opt:stage, self:provider.stage}"
      
resources:
  Resources:
    RateEventProcessingLoopOOMFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: /aws/lambda/rateEventProcessingLoop
        FilterPattern: "Runtime.OutOfMemory"
        MetricTransformations:
          - MetricNamespace: "Lambda/OOM"
            MetricName: "rateEventProcessingLoop_OOMErrorCount"
            MetricValue: "1"
            DefaultValue: 0

    RateEventProcessingLoopOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: RateEventProcessingLoopOOMFilter
      Properties:
        AlarmName: !Sub "${AWS::StackName}-rateEventProcessingLoop-OOM"
        AlarmDescription: !Sub "Lambda rateEventProcessingLoop OutOfMemory in ${AWS::Region}"
        Namespace: "Lambda/OOM"
        MetricName: "rateEventProcessingLoop_OOMErrorCount"
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}