service: customReplayLoop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

functions:
  customReplayLoop:
    handler: index.handler
    name: customReplayLoop
    description: ${env:VERSION_DESCRIPTION}
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    reservedConcurrency: 1
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: 'customReplayLoop_${opt:stage, self:provider.stage}'

resources:
  Resources:
    CustomReplayLoopOOMFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: /aws/lambda/customReplayLoop
        FilterPattern: "Runtime.OutOfMemory"
        MetricTransformations:
          - MetricNamespace: "Lambda/OOM"
            MetricName: "customReplayLoop_OOMErrorCount"
            MetricValue: "1"
            DefaultValue: 0

    CustomReplayLoopOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: CustomReplayLoopOOMFilter
      Properties:
        AlarmName: !Sub "${AWS::StackName}-customReplayLoop-OOM"
        AlarmDescription: !Sub "Lambda customReplayLoop OutOfMemory in ${AWS::Region}"
        Namespace: "Lambda/OOM"
        MetricName: "customReplayLoop_OOMErrorCount"
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}