service: nextgenMetadataLoop

package:
  artifact: dist/index.zip

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 900
  architecture: arm64
  logRetentionInDays: 60

custom:
  chainIDs:
    staging: 1
    prod: 1

functions:
  nextgenMetadataLoop:
    handler: index.handler
    name: nextgenMetadataLoop
    description: ${env:VERSION_DESCRIPTION}
    role: arn:aws:iam::987989283142:role/lambda-vpc-role
    reservedConcurrency: 1
    events:
      - schedule: rate(1 hour)
    vpc:
      securityGroupIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):security}
      subnetIds: ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):subnets}
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
      SENTRY_ENVIRONMENT: 'nextgenMetadataLoop_${opt:stage, self:provider.stage}'
      NEXTGEN_CHAIN_ID: ${self:custom.chainIDs.${opt:stage, self:provider.stage}, 1}


resources:
  Resources:
    NextgenMetadataLoopOOMFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: /aws/lambda/nextgenMetadataLoop
        FilterPattern: "Runtime.OutOfMemory"
        MetricTransformations:
          - MetricNamespace: "Lambda/OOM"
            MetricName: "nextgenMetadataLoop_OOMErrorCount"
            MetricValue: "1"
            DefaultValue: 0

    NextgenMetadataLoopOOMAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: NextgenMetadataLoopOOMFilter
      Properties:
        AlarmName: !Sub "${AWS::StackName}-nextgenMetadataLoop-OOM"
        AlarmDescription: !Sub "Lambda nextgenMetadataLoop OutOfMemory in ${AWS::Region}"
        Namespace: "Lambda/OOM"
        MetricName: "nextgenMetadataLoop_OOMErrorCount"
        Statistic: Sum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}
        OKActions:
          - ${file(../../serverless-config/${opt:stage, self:provider.stage}/vpc.js):cwtopic}